# https://taskfile.dev

version: '3'

vars:
  WITH_NIX: env PATH="$HOME/.nix-profile/bin:$PATH"

tasks:
  default:
    cmds:
      - task: ssh_key
      - task: display_ssh_key
      - task: dotfiles_git
      - task: devbox
      - task: set_shell
      - task: tmux
      - task: neovim

  ssh_key:
    vars:
      SSH_DIR: $HOME/.ssh
    cmds:
      - mkdir -p {{.SSH_DIR}}
      - cd {{.SSH_DIR}} && ssh-keygen -t ed25519 -f id_ed25519 -N "" && ls
    status:
      - test -f {{.SSH_DIR}}/id_ed25519

  display_ssh_key:
    vars:
      SSH_DIR: $HOME/.ssh
    cmds:
      - echo add your public key to github https://github.com/settings/keys
      - cat {{.SSH_DIR}}/id_ed25519.pub
      - echo  press ENTER when ok
      - read
    silent: true
    status:
      - ssh -T git@github.com 2>&1 | grep success

  devbox:
    cmds:
      - curl -fsSL https://get.jetpack.io/devbox | bash
      - devbox global install
    status:
      - test -f /usr/local/bin/devbox

  dotfiles_git:
    cmds:
      - git clone --bare git@github.com:gverger/home-dotfiles.git $HOME/.dotfiles
      - git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
    status:
      - test -d $HOME/.dotfiles

  set_shell:
    vars:
      ZSH_HOME: $HOME/.local/share/devbox/global/default/.devbox/nix/profile/default/bin
    cmds:
      - sudo bash -c "echo {{.ZSH_HOME}}/zsh >> /etc/shells"
      - chsh $USER -s {{.ZSH_HOME}}/zsh
    status:
      - cat /etc/shells | grep "{{.ZSH_HOME}}/zsh"

  neovim:
    cmds:
      - |
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
                                                               https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    status:
      - test -f $HOME/.local/share/nvim/site/autoload/plug.vim

  tmux:
    cmds:
      - |
        git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
    status:
      - test -d $HOME/.tmux/plugins/tpm
